# Generated by Django 5.2.7 on 2025-10-31 13:15

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.CharField(max_length=8)),
                ('exchange_date', models.DateField()),
                ('state', models.BooleanField(default=False)),
                ('room_code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=50)),
                ('msg', models.CharField(max_length=200)),
                ('budget', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=50)),
                ('ln', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=250)),
                ('pref', models.CharField(blank=True, max_length=250, null=True)),
                ('links', models.JSONField(blank=True, default=list, validators=[base.models.validate_items])),
            ],
        ),
    ]
