# Generated by Django 5.2.7 on 2025-10-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='code',
            field=models.CharField(default=11111, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
