# Generated by Django 5.2.7 on 2025-10-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_users_active_users_code_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='room_code',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
