# Generated by Django 5.2.7 on 2025-10-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_users_room_code_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='room_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
