# Generated by Django 5.2.7 on 2025-11-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_users_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='giftee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
