# Generated by Django 5.2.7 on 2025-11-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_users_giftee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='giftee',
            field=models.CharField(blank=True, null=True),
        ),
    ]
