# Generated by Django 5.2.7 on 2025-11-10 16:52

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_users_giftee'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ai_links',
            field=models.JSONField(blank=True, default=list, validators=[base.models.validate_items]),
        ),
    ]
