# Generated by Django 5.2.7 on 2025-11-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_users_ai_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='recovery_pass',
            field=models.CharField(default=None, max_length=7, null=True),
        ),
    ]
